### ISSUE TITLE
상품구매 시  InApp API 페이지 관련

### ISSUE THREAD

**Issue by kaskim** [ONE-store/inapp-sdk#10]
Application 실행 > 상점 > InApp API 페이지 진입 > 단말 홈 키 > Application 앱아이콘 터치 실행

위 상황시 InApp API 페이지가 사라져 재구매 시도시 -1004 ResultCode가 반환됩니다.

Application 실행 > 상점 > InApp API 페이지 진입 > 단말 홈 키 > 메뉴버튼으로 Application 실행

위 상황에서는 InApp API페이지가 사라지지 않습니다.

확인부탁드립니다.

**Comment by dusskapark** [comment]
본 이슈트래커는 원스토어에서 공식적으로 사용하지 않습니다. devhelper@onestore.co.kr 로 문의하세요 :)

**Comment by dusskapark** [comment]
아마 인앱 테스트 페이지(셀프테스트)의 문제로 보이네요. 실제 상용 결제에서도 똑같은 문제가 발생하는지를 devhelper@로
문의하시면 좋을 것 같습니다

**Comment by kaskim** [comment]
상용 결제 페이지, 개발용 테스트 페이지 둘다 똑같은 문제가 발생하고있네요. devhelper@ 메일은 답변이 없네요 .. ㅠ

**Comment by kaskim** [comment]
일단 이슈는 닫겠습니다
