### ISSUE TITLE
RequestPaymenet 에 들어가는 파라미터에 대해 설명부탁드립니다.

### ISSUE THREAD

**Issue by holymokee** [ONE-store/inapp-sdk#6]
// (1) appId
		// (2) productId
		// (3) proudtName
		// (4) tId
		// (5) bpInfo

이중 4,5은  어떤 값을 넣어야 하는건지 잘 모르겠습니다. 설명 부탁드립니다.

**Comment by dusskapark** [comment]
둘다 옵션값입니다. `TID`에 내부에서 사용하는 결제 seq 값을 넣어두면 나중에 대조하기 좋습니다.
