### ISSUE TITLE
플러그인 SDK에서 유니티로 메시지를 전달 문의

### ISSUE THREAD

**Issue by qraqra** [ONE-store/inapp-sdk#9]
결제 취소 시에 플러그인 SDK에서 유니티로 메시지를 전달하는 부분이 없는데, 저희가 서비스 하는 게임 구조상 그게 필요합니다. 혹 관련해서 참고 할 수 있는 내용이 있으면 알려주시면 좋겠습니다.

**Comment by dusskapark** [comment]
[devhelper@onestore.co.kr] 로 문의하셔야 합니다. :)
